<?php

/**
 * @file
 * Contains opeka.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Component\Utility\Crypt;
use Drupal\Core\Template\Attribute;

/**
 * Implements template_preprocess_html().
 *
 * Adds user permission classes to body
 */
function opeka_preprocess_html(&$vars) {
  $user = \Drupal::currentUser();
  $opeka_role = "opeka-no-access";
  if ($user->hasPermission('administer opeka chat')) {
    $opeka_role = "opeka-counselor";
  }
  else if ($user->hasPermission('access opeka chat')) {
    $opeka_role = "opeka-client";
  }

  if (is_array($vars['attributes'])) {
    $vars['attributes'] = new Attribute();
  }
  $vars['attributes']->addClass($opeka_role);
}

/**
 * Implements hook_help().
 */
function opeka_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the opeka module.
    case 'help.page.opeka':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Secure anonymous chat system, built with Drupal and dnode.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function opeka_theme() {
  return [
    'opeka_chat' => [],
    'opeka_admin_chat' => [],
  ];
}

/**
 * Implements hook_library_info_build().
 */
function opeka_library_info_build() {
  $js_url = \Drupal::config('opeka.advanced_settings')->get('connectjs_url');
  $libraries = [
    'dnode.connect' => [
      'js' => [
        $js_url => ['type' => 'external'],
      ],
    ],
  ];
  return $libraries;
}

/**
 * Implements hook_preprocess_THEME().
 */
function opeka_preprocess_opeka_chat(&$variables) {
  $variables['#attached']['library'][] = 'opeka/chat';
  $variables['#attached']['drupalSettings']['opeka'] = _opeka_compile_javascript_settings();
  $variables['#attached']['drupalSettings']['opeka']['user']['admin'] = FALSE;
  $variables['#attached']['library'][] = 'opeka/dnode.connect';
}

/**
 * Implements hook_preprocess_THEME().
 */
function opeka_preprocess_opeka_admin_chat(&$variables) {
  $variables['#attached']['library'][] = 'opeka/admin.chat';
  $variables['#attached']['drupalSettings']['opeka'] = _opeka_compile_javascript_settings();
  $variables['#attached']['drupalSettings']['opeka']['user']['admin'] = TRUE;
  $variables['#attached']['library'][] = 'opeka/dnode.connect';
}

/**
 * Helper function for getting all relevant JS settings.
 */
function _opeka_compile_javascript_settings() {
  $opeka_adv_config = \Drupal::config('opeka.advanced_settings');

  $js_url = $opeka_adv_config->get('connectjs_url');
  $settings = $opeka_adv_config->get() + [
    'path' => base_path() . drupal_get_path('module', 'opeka'),
    'dnode_endpoint' => preg_replace('/\/connect[.]js$/', '/opeka', $js_url),
    'socket_io_url' => preg_replace('/\/connect[.]js$/', '/', $js_url),
    'user' => [
      'name' => \Drupal::currentUser()->getUsername(),
      'uid' => \Drupal::currentUser()->id(),
      'sid' => Crypt::hashBase64(\Drupal::service('session_manager')->getId()),
    ],
  ];

  return $settings;

}
