#!/bin/bash
# Script to start the node server for the cfdpchat-app
# Depends on an upstart script placed in /etc/init
# authors: Daniel Mois and Benjamin Christensen

echo -e "Starting CfDP Chat. \n";
sudo start cfdpchat-app;
