<?php

/**
 * @file
 * Drupal screening submodule for the Opeka project.
 *
 * Provides the screening questions management and rendering
 * functionality.
 */

/**
 * Implements hook_form_alter().
 *
 * We override the opeka admin settings form to add our screening questions
 */

/**
 * Implements hook_menu().
 */
function opeka_screening_questions_menu() {
  $items['admin/config/services/opeka/screening'] = array(
    'title' => 'Screening Questions',
    'type' => MENU_LOCAL_TASK,
    'weight' => 10,
    'description' => 'Provides settings for the screening questions.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('opeka_screening_questions_settings_form'),
    'access arguments' => array('administer site configuration'),
    'file' => 'opeka_screening_questions.admin.inc',
  );
  return $items;
}



/**
 * Implements hook_preprocess_page().
 */
function opeka_screening_questions_preprocess_page(&$vars) {
  $weekdays_options = opeka_screening_questions_weekdays();

  // Get the opening hours from the variables table.
  $opeka_screening_questions_datetimes_array = variable_get('opeka_screening_questions_datetimes', []);
  // Collapse all times into the same days.
  $opeka_screening_questions_datetimes_merged_days_array = [];
  foreach ($opeka_screening_questions_datetimes_array as $array_el) {
    $opeka_screening_questions_datetimes_merged_days_array[$array_el['day']][] = $array_el['times_from'] . '-' . $array_el['times_to'];
  }
  // Sort days following the order of the opeka_screening_questions_weekdays() array.
  $opeka_screening_questions_datetimes_merged_days_array = 
    array_replace(array_flip(array_keys($weekdays_options)), $opeka_screening_questions_datetimes_merged_days_array);
  // Render days and times into a simple list.
  $opeka_screening_questions_datetimes_list_array = [];
  foreach ($opeka_screening_questions_datetimes_merged_days_array as $day=>$times) {
    if (is_array($times)) {
      $opeka_screening_questions_datetimes_list_array[] = $weekdays_options[$day] . ": " . implode(', ', $times);
    }
  }
  // replace the opeka_schedule theme variable with our own render array.
  $vars['opeka_schedule'] = array(
    'message' => array(
      '#tag' => 'p',
      '#value' => variable_get('opeka_screening_questions_message', t('You can chat with the counselors according to the following schedule.')),
      '#theme' => 'html_tag',
    ),
    'list' => array(
      '#items' => $opeka_screening_questions_datetimes_list_array,
      '#theme' => 'item_list',
      '#type' => 'ul',
    )
  );
}

/**
 * @return string[]
 *   An array of all weekdays, localized.
 */
function opeka_screening_questions_weekdays() {
  return array(
    'monday' => t('Monday'),
    'tuesday' => t('Tuesday'),
    'wednesday' => t('Wednesday'),
    'thursday' => t('Thursday'),
    'friday' => t('Friday'),
  );
}
