<?php

/**
 * @file
 * Drupal schedule submodule for the Opeka project.
 *
 * Provides the opening hours management and rendering
 * functionality.
 */

/**
 * Implements hook_permission().
 */
function opeka_opening_hours_permission() {
  return array(
    'administer opeka opening hours' => array(
      'title' => t('Administer the Opeka opening hours'),
      'description' => t('Grants a user access to the admin backend for managing the Opeka Opening hours .'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function opeka_opening_hours_menu() {
  $items = array();

  $items['admin/config/services/opeka/opening_hours'] = array(
    'title' => 'Opening hours',
    'description' => 'Provides management options for the Opeka opening hours.',
    'type' => MENU_LOCAL_TASK,
    'weight' => 0,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('opeka_opening_hours_admin_form'),
    'access arguments' => array('administer opeka opening hours'),
    'file' => 'opeka_opening_hours.admin.inc',
    'file path' => drupal_get_path('module', 'opeka_opening_hours'),
  );
  return $items;
}


/**
 * Implements hook_preprocess_page().
 */
function opeka_opening_hours_preprocess_page(&$vars) {
  $weekdays_options = opeka_opening_hours_weekdays();

  // Get the opening hours from the variables table.
  $opeka_opening_hours_datetimes_array = variable_get('opeka_opening_hours_datetimes', []);
  // Collapse all times into the same days.
  $opeka_opening_hours_datetimes_merged_days_array = [];
  foreach ($opeka_opening_hours_datetimes_array as $array_el) {
    $opeka_opening_hours_datetimes_merged_days_array[$array_el['day']][] = $array_el['times_from'] . '-' . $array_el['times_to'];
  }
  // Sort days following the order of the opeka_opening_hours_weekdays() array.
  $opeka_opening_hours_datetimes_merged_days_array = 
    array_replace(array_flip(array_keys($weekdays_options)), $opeka_opening_hours_datetimes_merged_days_array);
  // Render days and times into a simple list.
  $opeka_opening_hours_datetimes_list_array = [];
  foreach ($opeka_opening_hours_datetimes_merged_days_array as $day=>$times) {
    if (is_array($times)) {
      $opeka_opening_hours_datetimes_list_array[] = $weekdays_options[$day] . ": " . implode(', ', $times);
    }
  }
  // replace the opeka_schedule theme variable with our own render array.
  $vars['opeka_schedule'] = array(
    'message' => array(
      '#tag' => 'p',
      '#value' => variable_get('opeka_opening_hours_message', t('You can chat with the counselors according to the following schedule.')),
      '#theme' => 'html_tag',
    ),
    'list' => array(
      '#items' => $opeka_opening_hours_datetimes_list_array,
      '#theme' => 'item_list',
      '#type' => 'ul',
    )
  );
}

/**
 * @return string[]
 *   An array of all weekdays, localized.
 */
function opeka_opening_hours_weekdays() {
  return array(
    'monday' => t('Monday'),
    'tuesday' => t('Tuesday'),
    'wednesday' => t('Wednesday'),
    'thursday' => t('Thursday'),
    'friday' => t('Friday'),
  );
}
